force-app/main/default/objects/Account/fields/Branch_Number__c.field-meta.xml
<CustomField>
    <fullName>Branch_Number__c</fullName>
    <label>Branch Number</label>
    <length>12</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Chamber_of_Commerce__c.field-meta.xml
<CustomField>
    <fullName>Chamber_of_Commerce__c</fullName>
    <label>Chamber of Commerce</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Date_of_Termination_Chamber_of_Commerce__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Termination_Chamber_of_Commerce__c</fullName>
    <label>Date of Termination Chamber of Commerce</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Is_Branch__c.field-meta.xml
<CustomField>
    <fullName>Is_Branch__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Branch</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Is_Main_Branch__c.field-meta.xml
<CustomField>
    <fullName>Is_Main_Branch__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Main Branch</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Legal_Form__c.field-meta.xml
<CustomField>
    <fullName>Legal_Form__c</fullName>
    <label>Legal Form</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CoCAccountRepository.cls
public inherited sharing class CoCAccountRepository implements ICoCAccountRepository {
    public Account getAccountById(Id accountId) {
        return [ SELECT  Id, Is_Branch__c, Branch_Number__c, Chamber_of_Commerce__c, Name, ShippingCity, 
                        ShippingStreet, ShippingPostalCode, Is_Main_Branch__c, BillingStreet, BillingPostalCode,
                        BillingCity, BillingCountry, Legal_form__c, Date_of_Termination_Chamber_of_Commerce__c
                FROM    Account
                WHERE   Id =: accountId];
    }

    public Database.SaveResult updateAccount(Account acc) {
        return Database.update(acc, false);
    }
}