force-app/main/default/objects/MappingDetail__mdt/MappingDetail__mdt.object-meta.xml
<CustomObject>
    <label>Mapping Detail</label>
    <pluralLabel>Mapping Details</pluralLabel>
</CustomObject>

force-app/main/default/objects/MappingDetail__mdt/fields/SalesforceField__c.field-meta.xml
<CustomField>
    <fullName>SalesforceField__c</fullName>
    <label>Salesforce Field</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MappingDetail__mdt/fields/SmartCompanyDataField__c.field-meta.xml
<CustomField>
    <fullName>SmartCompanyDataField__c</fullName>
    <label>SmartCompanyData Field</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>identifier</fullName>
                <default>true</default>
                <label>identifier</label>
            </value>
            <value>
                <fullName>branchIdentifier</fullName>
            </value>
            <value>
                <fullName>rsin</fullName>
            </value>
            <value>
                <fullName>name</fullName>
            </value>
            <value>
                <fullName>isBranch</fullName>
            </value>
            <value>
                <fullName>isMainBranch</fullName>
            </value>
            <value>
                <fullName>legalForm</fullName>
            </value>
            <value>
                <fullName>deregistrationDate</fullName>
            </value>
            <value>
                <fullName>city</fullName>
            </value>
            <value>
                <fullName>street</fullName>
            </value>
            <value>
                <fullName>houseNumber</fullName>
            </value>
            <value>
                <fullName>houseNumberAddition</fullName>
            </value>
            <value>
                <fullName>postalCode</fullName>
            </value>
            <value>
                <fullName>country</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/GetRecordCoCDetailsInvocable.cls
public with sharing class GetRecordCoCDetailsInvocable {
    
    @InvocableMethod(label='Get Record COC Details' description='Get Record COC Details')
    public static List<CoCRecordDetails> getRecordCoCDetails(List<InvocableCOCDataRequest> requests) {
        List <CoCRecordDetails> detailList = new List <CoCRecordDetails>();

        for (InvocableCOCDataRequest request : requests) {
            CoCRecordDetails details = new CoCRecordDetails();
            SObject originalRecord = SmartCompanyDataUtils.getSObjectRecordByFieldList(request.recordId, request.sObjectType, SmartCompanyDataUtils.retrieveFieldsFromMappingDetails(request.mappingDetail));
            
            for (mappingDetail__mdt md : request.mappingDetail) {
                if (md.SmartCompanyDataField__c == 'identifier')    {
                    details.identifier = (String)originalRecord.get(md.SalesforceField__c);
                }   
                if(md.SmartCompanyDataField__c == 'isBranch')   {
                    details.isBranch = (Boolean)originalRecord.get(md.SalesforceField__c);
                }
                if(md.SmartCompanyDataField__c == 'isMainBranch')   {
                    details.isMainBranch = (Boolean)originalRecord.get(md.SalesforceField__c);
                }
            }
            detailList.add(details);
        }
        return detailList;
    }

    public class CoCRecordDetails{
        @InvocableVariable
        public String identifier;
        @InvocableVariable
        public Boolean isBranch;
        @InvocableVariable
        public Boolean isMainBranch;
        @InvocableVariable
        public String branchNumber;
    }

    public class InvocableCOCDataRequest{
        @InvocableVariable public String recordId;
        @InvocableVariable public String identifier;
        @InvocableVariable public Boolean isBranch;
        @InvocableVariable public Boolean isMainBranch;
        @InvocableVariable public List<MappingDetail__mdt> mappingDetail;
        @InvocableVariable public String sObjectType;
    }

}