force-app/main/default/objects/MappingDetail__mdt/MappingDetail__mdt.object-meta.xml
<CustomObject>
    <label>Mapping Detail</label>
    <pluralLabel>Mapping Details</pluralLabel>
</CustomObject>

force-app/main/default/objects/MappingDetail__mdt/fields/SalesforceField__c.field-meta.xml
<CustomField>
    <fullName>SalesforceField__c</fullName>
    <label>Salesforce Field</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GetSObjectRecordByMappingInvocable.cls
public with sharing class GetSObjectRecordByMappingInvocable {
    @InvocableMethod(label='Get fields of record' description='Gets fields based on the Id, Mtd')
    public static List<SObject> getSObjectRecordByMapping(List<SObjectRecordByMappingRequest> sObjByMappingList) {
        List<SObject> sObjectList = new List<SObject>();
        for(SObjectRecordByMappingRequest request : sObjByMappingList){
            List<String> fieldList = new List<String>();
            for(MappingDetail__mdt md : request.mappingDetailList){
                fieldList.add(md.SalesforceField__c);
            }
            sObjectList.add(SmartCompanyDataUtils.getSObjectRecordByFieldList(request.recordId, request.sObjectType, fieldList));
        }
        return sObjectList;
    }
    
}